components: 
  securitySchemes:
    AuthorizationToken:
      bearerFormat: nonce token or JWT
      description: OAuth Bearer Token - A valid Bearer token to prove authorization
      scheme: bearer
      type: http
info:
  description: 'The Breeding API (BrAPI) is a Standardized RESTful Web Service API Specification for communicating Plant Breeding Data. BrAPI allows for easy data sharing between databases and tools involved in plant breeding.


    <strong>General Reference Documentation</strong>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/URL_Structure.md">URL Structure</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md">Response Structure</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Date_Time_Encoding.md">Date/Time Encoding</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Location_Encoding.md">Location Encoding</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Error_Handling.md">Error Handling</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Search_Services.md">Search Services</a>


    <a href="https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Asychronous_Processing.md">Asynchronous Processing</a>'
  title: BrAPI
  version: '1.3'
openapi: 3.0.0
paths: {}
security:
- AuthorizationToken: []
servers:
- url: https://test-server.brapi.org/brapi/v1
tags:
- description: GA4GH Schema
  externalDocs:
    description: Docs
    url: https://ga4gh-schemas.readthedocs.io/en/latest/api/index.html
  name: GA4GH
- description: Check the available calls on a server
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Calls
- description: Information about Crops
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Crops
- description: Information about Programs
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Programs
- description: Information about Locations
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Locations
- description: Information about Trials
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Trials
- description: Information about Studies
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Studies
- description: Information about Observations
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Observations
- description: API to retrieve list and details of observation variables. An observation variable is composed by the unique combination of one Trait, one Method and one Scale.
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Observation Variables
- description: Information about Phenotypes
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Phenotypes
- description: Information about Germplasm
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Germplasm
- description: Information about Germplasm Attributes
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Germplasm Attributes
- description: Information about Markers
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Markers
- description: Information about Marker Profiles
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Marker Profiles
- description: Information about Genome Maps
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Genome Maps
- description: Information about Samples
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Samples
- description: 'This interface is specific to facilities that performs an external analysis, such as genotyping facilities. The interface should be implemented by that facility''s server. The breeding database is the client of this interface.

    Note that to use these calls, you likely have to use the authentication call prior to connecting (see Authentication best practices).'
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Vendor
- description: Create and manipulate generic lists
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Lists
- description: Create and manipulate image data
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Images
- description: Create and manipulate information about people
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: People
- description: The available Search Services for finding data
  externalDocs:
    description: Docs
    url: https://wiki.brapi.org/
  name: Search Services
